//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int restaurantId { get; set; }
        [DisplayName("Restaurant Name")][Required]
        public string name { get; set; }
        [DisplayName("Street Number")][Required]
        public string streetNumber { get; set; }
        [DisplayName("Street Name")][Required]
        public string streetName { get; set; }
        [DisplayName("City")][Required]
        public string city { get; set; }
        [DisplayName("Postal Code")][Required]
        public string postal_code { get; set; }
        [DisplayName("Geo-Location")]
        public System.Data.Entity.Spatial.DbGeography location { get; set; }
        [DisplayName("Genre")][Required]
        public string genre { get; set; }
        [DisplayName("Price")][Required]
        [RegularExpression(@"^\${1,4}$", ErrorMessage="Please use $ to $$$$ to rate the restaurant.")]
        public string price { get; set; }
        [DisplayName("Views")]
        public Nullable<int> views { get; set; }
        [DisplayName("Added Date")]
        public System.DateTime added_date { get; set; }
        [DisplayName("Added By")]
        public string added_by { get; set; }
        [DisplayName("Edit Date")]
        public Nullable<System.DateTime> edit_date { get; set; }
        [DisplayName("Edited By")]
        public string edited_by { get; set; }


        [DisplayName("Reviews")]
        public int numOfReviews { get; set; }
        [DisplayName("Average Rating")]
        public double avgRating { get; set; }

    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
