//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        public int reviewId { get; set; }
        [DisplayName("Title")][Required]
        public string title { get; set; }
        [DisplayName("Review date")]
        public System.DateTime date { get; set; }
        public int restaurantId { get; set; }
        [DisplayName("Reviewed by")]
        public string reviewed_by { get; set; }
        [DisplayName("Rating")][Required][Range(1,5)]
        public int rating { get; set; }
        [DisplayName("Review content")][Required]
        public string content { get; set; }

        public int averageRating { get; set; }

        public int numOfReviews { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
    }
}
