//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Restaurants = new HashSet<Restaurant>();
            this.Restaurants1 = new HashSet<Restaurant>();
            this.Reviews = new HashSet<Review>();
        }
    
        public string username { get; set; }
        [DataType(DataType.Password)]
        public string password { get; set; }
    
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual ICollection<Restaurant> Restaurants1 { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
