//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public UserDetail()
        {
            this.Restaurants = new HashSet<Restaurant>();
            this.Restaurants1 = new HashSet<Restaurant>();
        }
    
        public string username { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string imgPath { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        public virtual ICollection<Restaurant> Restaurants1 { get; set; }
    }
}
